version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install firebase-tools
          command: yarn add --dev firebase-tools
      - run:
          name: Yarn Install
          command: yarn
      - run:
          name: Build
          command: yarn generate
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2.1
  deployment:
    jobs:
      - build:
          filters:
            branches:
              only: master