version: 2.1
jobs:
  deploy-dev:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install firebase-tools
          command: yarn add --dev firebase-tools
      - run:
          name: Yarn Install
          command: yarn
      - run:
          name: Build
          command: yarn generate
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --project dev --token=$FIREBASE_TOKEN

  deploy-prod:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install firebase-tools
          command: yarn add --dev firebase-tools
      - run:
          name: Yarn Install
          command: yarn
      - run:
          name: Build
          command: yarn generate
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --project prod --token=$FIREBASE_TOKEN


workflows:
  version: 2.1
  deployment:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: develop
      - deploy-dev:
          filters:
            branches:
              only: master